### PR TITLE
[Xcode] Set MACOSX_DEPLOYMENT_TARGET on open source builds to match the system version

### PR DESCRIPTION
**Pull request by emw-apple**
#### 4bd1b259bd375b8ace4ad8c9cfaea66679c53663
<pre>
[Xcode] Set MACOSX_DEPLOYMENT_TARGET on open source builds to match the system version
<a href="https://bugs.webkit.org/show_bug.cgi?id=252783">https://bugs.webkit.org/show_bug.cgi?id=252783</a>
rdar://problem/105812206

Reviewed by NOBODY (OOPS!).

When building without an internal SDK, set MACOSX_DEPLOYMENT_TARGET to
the system major version, instead of whatever version corresponds to the
SDK. This means WebKit will produce runnable artifacts on Xcode
distributions which build for a different OS version than they run on.

Unfortunately, there is no automatic way in xcconfig to map from
six-digit version integers (e.g. 130000) to SDK versions (e.g. 13.0), so
this changes requires adding a mapping table.

* Configurations/SDKVariant.xcconfig:
* Configurations/WebKitTargetConditionals.xcconfig:
</pre>
https://github.com/WebKit/WebKit/commit/4ebecf04e6dbc47ad8f35f42e8daf6b2b3d3dd1e

| Misc | iOS, tvOS & watchOS  | macOS  | Linux |  Windows |
| ----- | ---------------------- | ------- |  ----- |  --------- |
| [✅ 🧪 style](https://ews-build.webkit.org/#/builders/38/builds/6672 "Passed style check") | [✅ 🛠 ios](https://ews-build.webkit.org/#/builders/26/builds/6888 "Built successfully") | [✅ 🛠 mac](https://ews-build.webkit.org/#/builders/14/builds/7070 "Built successfully") | [✅ 🛠 wpe](https://ews-build.webkit.org/#/builders/5/builds/8261 "Built successfully") | [✅ 🛠 wincairo](https://ews-build.webkit.org/#/builders/32/builds/6945 "Built successfully") 
| | [✅ 🛠 ios-sim](https://ews-build.webkit.org/#/builders/23/builds/7976 "Built successfully") | [❌ 🛠 mac-AS-debug](https://ews-build.webkit.org/#/builders/16/builds/6834 "Failed to compile WebKit") | [✅ 🧪 wpe-wk2](https://ews-build.webkit.org/#/builders/34/builds/9842 "Passed tests") | 
| [✅ 🧪 webkitperl](https://ews-build.webkit.org/#/builders/11/builds/6790 "Passed tests") | [✅ 🧪 ios-wk2](https://ews-build.webkit.org/#/builders/15/builds/7323 "Passed tests") | [✅ 🧪 api-mac](https://ews-build.webkit.org/#/builders/18/builds/6115 "Passed tests") | [✅ 🛠 gtk](https://ews-build.webkit.org/#/builders/2/builds/8350 "Built successfully") | 
| | [✅ 🧪 ios-wk2-wpt](https://ews-build.webkit.org/#/builders/39/builds/4785 "Passed tests") | | [✅ 🧪 gtk-wk2](https://ews-build.webkit.org/#/builders/1/builds/13860 "Passed tests") | 
| | [✅ 🧪 api-ios](https://ews-build.webkit.org/#/builders/13/builds/6576 "Passed tests") | [✅ 🧪 mac-wk2](https://ews-build.webkit.org/#/builders/36/builds/6123 "Passed tests") | [✅ 🧪 api-gtk](https://ews-build.webkit.org/#/builders/21/builds/8810 "Passed tests") | 
| | [✅ 🛠 tv](https://ews-build.webkit.org/#/builders/7/builds/6603 "Built successfully") | [❌ 🧪 mac-AS-debug-wk2](https://ews-build.webkit.org/#/builders/16/builds/6834 "Failed to compile WebKit") | | 
| | [✅ 🛠 tv-sim](https://ews-build.webkit.org/#/builders/30/builds/5998 "Built successfully") | | | 
| | [✅ 🛠 watch](https://ews-build.webkit.org/#/builders/4/builds/10170 "Built successfully") | | | 
| | [✅ 🛠 watch-sim](https://ews-build.webkit.org/#/builders/31/builds/6371 "Built successfully") | | |

### CODE REVIEW

**Comment by emw-apple** [comment]
```
In file included from /Volumes/Data/worker/macOS-AppleSilicon-Ventura-Debug-Build-EWS/build/WebKitBuild/Debug/DerivedSources/WebCore/unified-sources/UnifiedSource25.cpp:15:
/Volumes/Data/worker/macOS-AppleSilicon-Ventura-Debug-Build-EWS/build/WebKitBuild/Debug/DerivedSources/WebCore/JSApplePayFeature.cpp:63:56: error: no member named 'PaymentRequestDeferred' in 'WebCore::ApplePayFeature'; did you mean 'PaymentRequestRecurring'?
    static_assert(static_cast<size_t>(ApplePayFeature::PaymentRequestDeferred) == 8, "ApplePayFeature::PaymentRequestDeferred is not 8 as expected");
                                      ~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~
                                                       PaymentRequestRecurring
```

This is generated from IDLs and is new in 13.3. It should be behind `ENABLE(APPLE_PAY_DEFERRED_PAYMENTS)` guards, which are in turn based on `HAVE(PASSKIT_DEFERRED_PAYMENTS)`, which is defined as
```c
#if (PLATFORM(MAC) && __MAC_OS_X_VERSION_MIN_REQUIRED >= 130300) || (PLATFORM(IOS) && __IPHONE_OS_VERSION_MAX_ALLOWED >= 160400)
#define HAVE_PASSKIT_DEFERRED_PAYMENTS 1
#endif
```

Maybe the open-source build on 13.0 has broken since this landed?

**Comment by mohd-akram** [comment]
What's the status of this? Ran into this issue (crashing) after building on macOS 15 with the 26 SDK...
