### PR TITLE
[Build Speed] Simplify WTF::Variant

### PR DESCRIPTION
**Pull request by geoffreygaren**
#### 097a8276c97afa7e42b6e901bbe5e100af33ae48
<pre>
[Build Speed] Simplify WTF::Variant
<a href="https://bugs.webkit.org/show_bug.cgi?id=315055">https://bugs.webkit.org/show_bug.cgi?id=315055</a>
<a href="https://rdar.apple.com/177382367">rdar://177382367</a>

Reviewed by Brent Fulgham.

Saves 30s (5%) wall time in a clean build.

mpark::variant, like std::variant, uses O(n) and O(n^2) template instantiation
to support pre-C++20, plus edge case features we don&apos;t use in WebKit:

    * constexpr construction with a non-empty initializer

    * precise std library feature detection for degenerate copyable / movable
    combinations (e.g. a type that can move-construct but can&apos;t move-assign)

    * precise std library feature detection for degenerate trivial combinations
    (e.g. a type that has a non-trivial constructor but a trivial destructor)

Since we&apos;re overriding std::variant anyway, let&apos;s take the opportunity to
improve compile time.

This patch replaces the giant dispatcher switch with C++20 parameter pack
expansion, and a recursive union with a simple byte buffer.

This changes edge case constexpr and degenerate feature detection like so:

    * A non-empty Variant initializer is no longer constexpr.

    * If T has copy / move constructors, then Variant&lt;T&gt; is copyable / movable
    (even if T has no copy / move assignment operators).

    * If T has any non-trivial special member functions, then Variant&lt;T&gt; is
    non-trivial (even if T has some trivial special member functions).

These are good defaults because they meet all existing use cases and dramatically
improve compile time.

If a future use case wants the edge case features above, and is willing to
spend O(n^2) time to get them, that case can use std::variant.

No regressions in upstream mpark::variant tests, with the exception of the
constexpr thing. (The other two things are so edge-case-y that they aren&apos;t even
tested.)

* Source/WTF/wtf/Variant.h:
* Tools/TestWebKitAPI/Tests/WTF/Expected.cpp:

Canonical link: <a href="https://commits.webkit.org/313528@main">https://commits.webkit.org/313528@main</a>
</pre>

https://github.com/WebKit/WebKit/commit/ab8429610eb8339b45ca8e9614138cb8d9f38f1d

| Misc | iOS, visionOS, tvOS & watchOS  | macOS  | Linux |  Windows | Apple Internal |
| ----- | ---------------------- | ------- |  ----- |  --------- | ------ |
| [❌ 🧪 style](https://ews-build.webkit.org/#/builders/38/builds/163289 "161 style errors") | [✅ 🛠 ios](https://ews-build.webkit.org/#/builders/159/builds/36772 "Built successfully") | [✅ 🛠 mac](https://ews-build.webkit.org/#/builders/168/builds/29987 "Built successfully") | [✅ 🛠 wpe](https://ews-build.webkit.org/#/builders/5/builds/172228 "Built successfully") | [✅ 🛠 win](https://ews-build.webkit.org/#/builders/59/builds/119736 "Built successfully") | [✅ 🛠 ios-apple](https://ews-bridge.webkit.apple.com/builds/sw/T-276/9e3e4f99-fedf-4da3-8a91-4b42e965e839/1be76f08-6619-4cc0-a21e-b0fdfd493ace) 
| [✅ 🧪 bindings](https://ews-build.webkit.org/#/builders/9/builds/165158 "Passed tests") | [✅ 🛠 ios-sim](https://ews-build.webkit.org/#/builders/155/builds/37099 "Built successfully") | [✅ 🛠 mac-AS-debug](https://ews-build.webkit.org/#/builders/156/builds/36772 "Built successfully") | [✅ 🧪 wpe-wk2](https://ews-build.webkit.org/#/builders/34/builds/126806 "Passed tests") | [❌ 🧪 win-tests](https://ews-build.webkit.org/#/builders/60/builds/89393 "1 flakes 2 failures") | [✅ 🛠 mac-apple](https://ews-bridge.webkit.apple.com/builds/sw/T-276/9e3e4f99-fedf-4da3-8a91-4b42e965e839/eb10161a-1399-46b5-83b3-dbb12a11913a) 
| [✅ 🧪 webkitperl](https://ews-build.webkit.org/#/builders/11/builds/166248 "Passed tests") | [✅ 🧪 ios-wk2](https://ews-build.webkit.org/#/builders/162/builds/29078 "Passed tests") | [✅ 🧪 api-mac](https://ews-build.webkit.org/#/builders/18/builds/146799 "Passed tests") | [✅ 🧪 api-wpe](https://ews-build.webkit.org/#/builders/41/builds/107373 "Passed tests") | | [✅ 🛠 vision-apple](https://ews-bridge.webkit.apple.com/builds/sw/T-276/9e3e4f99-fedf-4da3-8a91-4b42e965e839/d2c108d8-7416-47a3-8361-76ee01064c1e) 
| | [  ~~🧪 ios-wk2-wpt~~](https://ews-build.webkit.org/#/builders/154/builds/28124 "The change is no longer eligible for processing. Pull Request was already closed when EWS attempted to process it.") | [✅ 🧪 api-mac-debug](https://ews-build.webkit.org/#/builders/165/builds/26748 "Passed tests") | [✅ 🛠 gtk3-libwebrtc](https://ews-build.webkit.org/#/builders/173/builds/19930 "Built successfully") | | 
| [✅ 🛠 🧪 jsc-x86-64](https://ews-build.webkit.org/#/builders/20/builds/155434 "Built successfully and passed tests") | [✅ 🧪 api-ios](https://ews-build.webkit.org/#/builders/13/builds/138018 "Passed tests") | [✅ 🧪 mac-wk1](https://ews-build.webkit.org/#/builders/167/builds/24523 "Passed tests") | [✅ 🛠 gtk](https://ews-build.webkit.org/#/builders/2/builds/174731 "Built successfully") | | 
| [✅ 🛠 🧪 jsc-debug-arm64](https://ews-build.webkit.org/#/builders/171/builds/24176 "Built successfully and passed tests") | [✅ 🛠 ios-safer-cpp](https://ews-build.webkit.org/#/builders/174/builds/27212 "Built successfully") | [✅ 🧪 mac-wk2](https://ews-build.webkit.org/#/builders/169/builds/26178 "Passed tests") | [✅ 🧪 gtk-wk2](https://ews-build.webkit.org/#/builders/1/builds/135106 "Passed tests") | | 
| | [✅ 🛠 vision](https://ews-build.webkit.org/#/builders/153/builds/36440 "Built successfully") | [✅ 🧪 mac-AS-debug-wk2](https://ews-build.webkit.org/#/builders/161/builds/30850 "Passed tests") | [✅ 🧪 api-gtk](https://ews-build.webkit.org/#/builders/21/builds/135098 "Passed tests") | | 
| | [✅ 🛠 vision-sim](https://ews-build.webkit.org/#/builders/160/builds/37227 "Built successfully") | [✅ 🧪 mac-wk2-stress](https://ews-build.webkit.org/#/builders/8/builds/146318 "Passed tests") | [✅ 🛠 playstation](https://ews-build.webkit.org/#/builders/134/builds/99167 "Built successfully") | | 
| [✅ 🛠 🧪 unsafe-merge](https://ews-build.webkit.org/#/builders/22/builds/24865 "Built successfully and passed tests") | [✅ 🧪 vision-wk2](https://ews-build.webkit.org/#/builders/164/builds/30403 "Passed tests") | [✅ 🧪 mac-intel-wk2](https://ews-build.webkit.org/#/builders/170/builds/23163 "Passed tests") | [✅ 🛠 jsc-armv7](https://ews-build.webkit.org/#/builders/35/builds/195691 "Built successfully") | | 
| | [✅ 🛠 tv](https://ews-build.webkit.org/#/builders/158/builds/35936 "Built successfully") | [✅ 🛠 mac-safer-cpp](https://ews-build.webkit.org/#/builders/120/builds/108660 "Built successfully") | [✅ 🧪 jsc-armv7-tests](https://ews-build.webkit.org/#/builders/25/builds/51019 "Passed tests") | | 
| | [✅ 🛠 tv-sim](https://ews-build.webkit.org/#/builders/157/builds/35435 "Built successfully") | [✅ 🧪 mac-site-isolation](https://ews-build.webkit.org/#/builders/185/builds/1188 "Passed tests") | | | 
| | [✅ 🛠 watch](https://ews-build.webkit.org/#/builders/163/builds/35682 "Built successfully") | | | | 
| | [✅ 🛠 watch-sim](https://ews-build.webkit.org/#/builders/152/builds/35583 "Built successfully") | | | |

### CODE REVIEW

**Review by brentfulgham — APPROVED** [review]
rs=me, assuming tests pass. Do we have a performance A/B on this to confirm we don't regress a benchmark?

**Comment by geoffreygaren** [comment]
> rs=me, assuming tests pass. Do we have a performance A/B on this to confirm we don't regress a benchmark?

I _believe_ that I did not change the part that was relevant to perf originally (the fancy switchy switch vs jump table), but I will schedule an A/B job just in case.

**Comment by weinig** [comment]
I am conflicted about this proposal. A build speed up is good, but the Variant class is complex type, and we didn’t write it ourselves and we have zero testing for it. I also think deviating from the standard behavior is likely to lead to unexpected errors. 

I’d propose that we exhaust other avenues for dealing compile time before making behavior changing changes.

**Comment by geoffreygaren** [comment]
> and we didn’t write it ourselves and we have zero testing for it

I ran the upstream tests.

**Comment by kmiller68** [comment]
> If a future use case wants the edge case features above, and is willing to spend O(n^2) time to get them, that case can use std::variant.

I'm not convinced this is the way to go particularly for the constexpr initializer but I won't block this.

**Comment by geoffreygaren** [comment]
> I'm not convinced this is the way to go particularly for the constexpr initializer but I won't block this.

FWIW, P2996 and P3074 appear to address this in C++26. So if we're talking about potential future uses of consteval, we have a path forward.

**Comment by hwti** [comment]
This breaks the build with GCC 15.2.1 (Fedora 43) :
```
In file included from /home/src/upstream/webkit/Source/WTF/wtf/StdLibExtras.h:52,
                 from /home/src/upstream/webkit/Source/WTF/wtf/MallocCommon.h:29,
                 from /home/src/upstream/webkit/Source/WTF/wtf/FastMalloc.h:28,
                 from /home/src/upstream/webkit/Source/WTF/config.h:31,
                 from /home/src/upstream/webkit/Source/WTF/wtf/JSONValues.cpp:33:
/home/src/upstream/webkit/Source/WTF/wtf/Variant.h: In instantiation of ‘constexpr mpark::detail::base<Ts>::alt_at<I>& mpark::detail::base<Ts>::get_alt() const & [with long unsigned int I = 6; Ts = {std::monostate, bool, double, int, WTF::String, WTF::JSONImpl::Value::ObjectTypeTag, WTF::JSONImpl::Value::ArrayTypeTag}]’:
/home/src/upstream/webkit/Source/WTF/wtf/Variant.h:1475:66: error: use of built-in trait ‘__type_pack_element<I, std::monostate, bool, double, int, WTF::String, WTF::JSONImpl::Value::ObjectTypeTag, WTF::JSONImpl::Value::ArrayTypeTag>’ in function signature; use library traits instead
 1475 |       template <std::size_t I> inline constexpr const alt_at<I> &get_alt() const & noexcept {
      |                                                                  ^~~~~~~
/home/src/upstream/webkit/Source/WTF/wtf/Variant.h: In instantiation of ‘constexpr mpark::detail::base<Ts>::alt_at<I>& mpark::detail::base<Ts>::get_alt() const & [with long unsigned int I = 5; Ts = {std::monostate, bool, double, int, WTF::String, WTF::JSONImpl::Value::ObjectTypeTag, WTF::JSONImpl::Value::ArrayTypeTag}]’:
/home/src/upstream/webkit/Source/WTF/wtf/Variant.h:1475:66: error: use of built-in trait ‘__type_pack_element<I, std::monostate, bool, double, int, WTF::String, WTF::JSONImpl::Value::ObjectTypeTag, WTF::JSONImpl::Value::ArrayTypeTag>’ in function signature; use library traits instead
...
/home/src/upstream/webkit/Source/WTF/wtf/Variant.h: In instantiation of ‘constexpr mpark::detail::base<Ts>::alt_at<I>& mpark::detail::base<Ts>::get_alt() & [with long unsigned int I = 6; Ts = {std::monostate, bool, double, int, WTF::String, WTF::JSONImpl::Value::ObjectTypeTag, WTF::JSONImpl::Value::ArrayTypeTag}]’:
/home/src/upstream/webkit/Source/WTF/wtf/Variant.h:1472:60: error: use of built-in trait ‘__type_pack_element<I, std::monostate, bool, double, int, WTF::String, WTF::JSONImpl::Value::ObjectTypeTag, WTF::JSONImpl::Value::ArrayTypeTag>’ in function signature; use library traits instead
 1472 |       template <std::size_t I> inline constexpr alt_at<I> &get_alt() & noexcept {
      |                                                            ^~~~~~~
...
```
I created #65293 for this.
